//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLMamNonEntities : DbContext
    {
        public QLMamNonEntities()
            : base("name=QLMamNonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<child> children { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<dish> dishes { get; set; }
        public virtual DbSet<fixture> fixtures { get; set; }
        public virtual DbSet<kitchen> kitchens { get; set; }
        public virtual DbSet<kitchen_provider> kitchen_provider { get; set; }
        public virtual DbSet<lesson> lessons { get; set; }
        public virtual DbSet<lesson_plan> lesson_plan { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<menu_dish> menu_dish { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<position> positions { get; set; }
        public virtual DbSet<position_role> position_role { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<revenue_expenditure> revenue_expenditure { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<salary> salaries { get; set; }
        public virtual DbSet<staff_teacher> staff_teacher { get; set; }
    }
}
