//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fixture
    {
        public long id { get; set; }
        public Nullable<long> id_category_fixtures { get; set; }
        public string name { get; set; }
        public Nullable<int> remain_quantity { get; set; }
        public Nullable<int> lose_quantity { get; set; }
    }
}
