//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitchen_provider
    {
        public long id { get; set; }
        public Nullable<long> id_kitchen { get; set; }
        public Nullable<long> id_provider { get; set; }
    
        public virtual kitchen kitchen { get; set; }
        public virtual provider provider { get; set; }
    }
}
