//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lesson
    {
        public long id { get; set; }
        public Nullable<long> id_plan { get; set; }
        public Nullable<long> id_staff { get; set; }
        public string name { get; set; }
        public string content { get; set; }
        public Nullable<System.TimeSpan> time_start { get; set; }
        public Nullable<System.TimeSpan> time_end { get; set; }
    
        public virtual lesson_plan lesson_plan { get; set; }
        public virtual staff_teacher staff_teacher { get; set; }
    }
}
