//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_dish
    {
        public long id { get; set; }
        public Nullable<long> id_menu { get; set; }
        public Nullable<long> id_dish { get; set; }
    
        public virtual dish dish { get; set; }
        public virtual menu menu { get; set; }
    }
}
