//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTN_QL_MamNon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public long id { get; set; }
        public Nullable<long> id_customer { get; set; }
        public Nullable<long> id_child { get; set; }
        public Nullable<int> quantity_months { get; set; }
        public Nullable<double> tuition_fees { get; set; }
        public Nullable<System.DateTime> payment_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual child child { get; set; }
        public virtual customer customer { get; set; }
    }
}
